# Allow all local connections
local   all             all                     trust

# Allow app connections over scram-sha-256
host    all             all             0.0.0.0/0               scram-sha-256

# Allow the replicator for replication
host    replication     replicator      0.0.0.0/0               scram-sha-256
