# Allow all local connections
local   all             all                     trust

# Allow app connections over scram-sha-256
host    all             postgres             all               scram-sha-256

# Allow the replicator for replication
host    replication     replicator      10.0.0.0/16              scram-sha-256
host    all             replicator      10.0.0.0/16              trust
