version: '3.8'

# Файл для быстрой разработки, который перезаписывает некоторые настройки из основного docker-compose.yml

x-build-args: &build-args
  BUILDKIT_INLINE_CACHE: 1
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  SKIP_TESTS: "true" # Пропускаем тесты в режиме разработки

x-microservice-dev-common: &microservice-dev-common
  # Монтируем локальный Gradle кэш для ускорения разработки
  volumes:
    - ~/.gradle:/home/gradle/.gradle
  # Для режима разработки уменьшаем количество реплик до 1
  deploy:
    replicas: 1
    resources:
      limits:
        cpus: "0.75"
        memory: 512M
  # Добавляем горячую перезагрузку через объем для исходного кода
  environment:
    - SPRING_PROFILES_ACTIVE=dev

services:
  # Публичные сервисы
  auth-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  user-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  notification-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  challenges-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  club-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  # Внутренние сервисы
  payment-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  stats-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  gamification-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common

  log-service:
    build:
      args:
        <<: *build-args
    <<: *microservice-dev-common 